# Dataanalys #

Här går vi igenom datan som vi hämtar från rikstans databas som kommer att användas för att träna modellerna.

In [1]:
import numpy as np
import pandas as pd

In [2]:
members.info()
print(members.head())
print(members['parti'].unique())

NameError: name 'members' is not defined

In [3]:
anforande_202324 = pd.read_csv(
    'documents/anforande-202324.csv',
    header=0,
    names = [
    'dok_id', 
    'dok_rm', 
    'dok_nummer', 
    'dok_datum', 
    'avsnittsrubrik', 
    'kammaraktivitet', 
    'anforande_nummer', 
    'talare', 
    'parti', 
    'intressent_id', 
    'rel_dok_id', 
    'replik'],
    dtype={
        'intressent_id': 'string'
    }
) 
anforande_202324["dok_id"].unique()

array(['HB09100', 'HB09101', 'HB09102', 'HB09103', 'HB09104', 'HB09105',
       'HB09106', 'HB09107', 'HB09108', 'HB09109', 'HB0911', 'HB09110',
       'HB09111', 'HB09112', 'HB09113', 'HB09114', 'HB09115', 'HB09116',
       'HB09117', 'HB09118', 'HB09119', 'HB0912', 'HB09120', 'HB09121',
       'HB09122', 'HB09123', 'HB09124', 'HB09125', 'HB09126', 'HB09128',
       'HB09129', 'HB0913', 'HB09130', 'HB09131', 'HB09132', 'HB09133',
       'HB09134', 'HB09135', 'HB09136', 'HB09137', 'HB09138', 'HB09139',
       'HB09140', 'HB09141', 'HB0915', 'HB0916', 'HB0917', 'HB0918',
       'HB0919', 'HB092', 'HB0920', 'HB0921', 'HB0922', 'HB0923',
       'HB0924', 'HB0925', 'HB0926', 'HB0927', 'HB0928', 'HB0929',
       'HB093', 'HB0930', 'HB0931', 'HB0932', 'HB0933', 'HB0934',
       'HB0935', 'HB0936', 'HB0937', 'HB0938', 'HB0939', 'HB094',
       'HB0940', 'HB0941', 'HB0942', 'HB0943', 'HB0944', 'HB0945',
       'HB0946', 'HB0947', 'HB0948', 'HB0949', 'HB095', 'HB0950',
       'HB0951', 'HB0952', 'HB0953', 'HB0954', 'HB0955', 'HB0956',
       'HB0957', 'HB0958', 'HB0959', 'HB096', 'HB0960', 'HB0961',
       'HB0962', 'HB0963', 'HB0964', 'HB0965', 'HB0966', 'HB0967',
       'HB0968', 'HB0969', 'HB097', 'HB0970', 'HB0971', 'HB0972',
       'HB0973', 'HB0975', 'HB0976', 'HB0977', 'HB0978', 'HB0979',
       'HB098', 'HB0980', 'HB0981', 'HB0982', 'HB0983', 'HB0984',
       'HB0985', 'HB0986', 'HB0987', 'HB0988', 'HB0989', 'HB099',
       'HB0990', 'HB0991', 'HB0992', 'HB0993', 'HB0994', 'HB0995',
       'HB0996', 'HB0997', 'HB0998', 'HB0999'], dtype=object)

In [18]:
print(anforande_202324[anforande_202324["dok_id"] == "HB09124"])

       dok_id   dok_rm  dok_nummer            dok_datum  \
2954  HB09124  2023/24         124  2024-05-29 00:00:00
2955  HB09124  2023/24         124  2024-05-29 00:00:00
2956  HB09124  2023/24         124  2024-05-29 00:00:00
2957  HB09124  2023/24         124  2024-05-29 00:00:00
2958  HB09124  2023/24         124  2024-05-29 00:00:00
...       ...      ...         ...                  ...
3028  HB09124  2023/24         124  2024-05-29 00:00:00
3029  HB09124  2023/24         124  2024-05-29 00:00:00
3030  HB09124  2023/24         124  2024-05-29 00:00:00
3031  HB09124  2023/24         124  2024-05-29 00:00:00
3032  HB09124  2023/24         124  2024-05-29 00:00:00

                                         avsnittsrubrik kammaraktivitet  \
2954  Vissa förslag om kompensation m.m. till person...    ärendedebatt
2955  Vissa förslag om kompensation m.m. till person...    ärendedebatt
2956  Vissa förslag om kompensation m.m. till person...    ärendedebatt
2957  Vissa förslag om kompensation m.m. till person...    ärendedebatt
2958  Vissa förslag om kompensation m.m. till person...    ärendedebatt
...                                                 ...             ...
3028  Riksrevisionens rapport om systemet för återka...    ärendedebatt
3029  Riksrevisionens rapport om systemet för återka...    ärendedebatt
3030  Riksrevisionens rapport om systemet för återka...    ärendedebatt
3031  Vissa förslag om kompensation m.m. till person...    ärendedebatt
3032  Vissa förslag om kompensation m.m. till person...    ärendedebatt

      anforande_nummer                 talare                  parti  \
2954                 1      Patrik Björck (S)                      S
2955                10      Patrik Björck (S)                      S
2956                11    Erik Hellsborn (SD)                     SD
2957                12   Crister Carlsson (M)                      M
2958                13      Patrik Björck (S)                      S
...                ...                    ...                    ...
3028                77   Annika Hirvonen (MP)                     MP
3029                78     Mauricio Rojas (L)                      L
3030                79   Annika Hirvonen (MP)                     MP
3031                 8  TREDJE VICE TALMANNEN  TREDJE VICE TALMANNEN
3032                 9   Crister Carlsson (M)                      M

      intressent_id rel_dok_id replik
2954  0516528386117  HB01SkU23      N
2955  0516528386117  HB01SkU23      Y
2956  0362779191527  HB01SkU23      N
2957  0387230530213  HB01SkU23      N
2958  0516528386117  HB01SkU23      Y
...             ...        ...    ...
3028  0819601620927  HB01SfU17      Y
3029  0591055036519  HB01SfU17      Y
3030  0819601620927  HB01SfU17      Y
3031  0155487380917  HB01SkU23      N
3032  0387230530213  HB01SkU23      Y

[79 rows x 12 columns]

In [8]:
anforande_202223

,dok_id,dok_rm,dok_nummer,dok_datum,avsnittsrubrik,kammaraktivitet,anforande_nummer,talare,parti,intressent_id,rel_dok_id,replik
0,HA091,2022/23,1,2022-09-26 00:00:00,Val av förste vice talman,NaN,10,Gunilla Carlsson (S),S,0875221317013,NaN,N
1,HA091,2022/23,1,2022-09-26 00:00:00,Val av förste vice talman,NaN,11,Annie Lööf (C),C,0862868280923,NaN,N
2,HA091,2022/23,1,2022-09-26 00:00:00,Val av andre vice talman,NaN,12,Henrik Vinge (SD),SD,0406831930624,NaN,N
3,HA091,2022/23,1,2022-09-26 00:00:00,Val av andre vice talman,NaN,13,Annika Hirvonen (MP),MP,0819601620927,NaN,N
4,HA091,2022/23,1,2022-09-26 00:00:00,Val av andre vice talman,NaN,14,SAMUEL GONZALEZ WESTLING (V),V,<NA>,NaN,N
...,...,...,...,...,...,...,...,...,...,...,...,...
12474,HA0999,2022/23,99,2023-04-27 00:00:00,Frågestund,frågestund,95,Per-Arne Håkansson (S),S,0630820052511,HAC120230427fs,N
12475,HA0999,2022/23,99,2023-04-27 00:00:00,Frågestund,frågestund,96,Energi- och näringsministern Ebba Busch (KD),KD,0512510717328,HAC120230427fs,N
12476,HA0999,2022/23,99,2023-04-27 00:00:00,Frågestund,frågestund,97,Carita Boulwén (SD),SD,0371882294919,HAC120230427fs,N
12477,HA0999,2022/23,99,2023-04-27 00:00:00,Frågestund,frågestund,98,Statsrådet Anna Tenje (M),M,0476336341120,HAC120230427fs,N
12478,HA0999,2022/23,99,2023-04-27 00:00:00,Frågestund,frågestund,99,Malin Larsson (S),S,0203877548421,HAC120230427fs,N

In [5]:
votering_202223 = pd.read_csv('documents/votering-202223.csv')
votering_202223.info()
print(votering_202223.columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196835 entries, 0 to 196834
Data columns (total 14 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   2022/23                               196835 non-null  object
 1   UU15                                  196835 non-null  object
 2   008484EA-7970-4559-BEA7-E2F6454E7571  196835 non-null  object
 3   5                                     196835 non-null  int64
 4   Julia Kronlid                         196835 non-null  object
 5   0638497389621                         196835 non-null  int64
 6   SD                                    196835 non-null  object
 7   Stockholms län                        196835 non-null  object
 8   Frånvarande                           196835 non-null  object
 9   sakfrågan                             196835 non-null  object
 10  2                                     196835 non-null  int64
 11  kvinna                                196835 non-null  object
 12  1980                                  196835 non-null  int64
 13  2023-05-10                            196835 non-null  object
dtypes: int64(4), object(10)
memory usage: 21.0+ MB
Index(['2022/23', 'UU15', '008484EA-7970-4559-BEA7-E2F6454E7571', '5',
       'Julia Kronlid', '0638497389621', 'SD', 'Stockholms län', 'Frånvarande',
       'sakfrågan', '2', 'kvinna', '1980', '2023-05-10'],
      dtype='object')

In [6]:
votering_columns = [
    'rm',
    'beteckning',
    'votering_id',
    'punkt',
    'namn',
    'intressent_id',
    'parti',
    'valkrets',
    'rost',
    'avser',
    'banknummer',
    'kön',
    'fodd',
    'system_datum'
]
votering_202223 = pd.read_csv(
    'documents/votering-202223.csv',
    header=0,
    names=votering_columns,
    dtype={ 'intressent_id': 'string' }
)

votering_202223

,rm,beteckning,votering_id,punkt,namn,intressent_id,parti,valkrets,rost,avser,banknummer,kön,fodd,system_datum
0,2022/23,UU15,008484EA-7970-4559-BEA7-E2F6454E7571,5,Helena Bouveng,0729710260118,M,Jönköpings län,Ja,sakfrågan,10,kvinna,1962,2023-05-10
1,2022/23,UU15,008484EA-7970-4559-BEA7-E2F6454E7571,5,Mattias Jonsson,0499755198526,S,Göteborgs kommun,Ja,sakfrågan,18,man,1974,2023-05-10
2,2022/23,UU15,008484EA-7970-4559-BEA7-E2F6454E7571,5,Merit Frost Lindberg,0533104339313,M,Stockholms kommun,Ja,sakfrågan,26,kvinna,1973,2023-05-10
3,2022/23,UU15,008484EA-7970-4559-BEA7-E2F6454E7571,5,Jimmie Åkesson,051207517226,SD,Jönköpings län,Frånvarande,sakfrågan,34,man,1979,2023-05-10
4,2022/23,UU15,008484EA-7970-4559-BEA7-E2F6454E7571,5,Maj Karlsson,0198917587520,V,Göteborgs kommun,Frånvarande,sakfrågan,42,kvinna,1980,2023-05-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196830,2022/23,CU6,FFC81C4F-0CB8-4972-A18D-4E4C62BFC19B,23,Carl B Hamilton,0477013214601,L,Stockholms kommun,Frånvarande,sakfrågan,316,man,1946,2023-04-19
196831,2022/23,CU6,FFC81C4F-0CB8-4972-A18D-4E4C62BFC19B,23,Rebecka Le Moine,0546731406922,MP,Östergötlands län,Avstår,sakfrågan,324,kvinna,1990,2023-04-19
196832,2022/23,CU6,FFC81C4F-0CB8-4972-A18D-4E4C62BFC19B,23,Emma Ahlström Köster,0360160202728,M,Skåne läns södra,Ja,sakfrågan,332,kvinna,1987,2023-04-19
196833,2022/23,CU6,FFC81C4F-0CB8-4972-A18D-4E4C62BFC19B,23,Camilla Hansén,0692076685824,MP,Örebro län,Avstår,sakfrågan,340,kvinna,1976,2023-04-19
196834,2022/23,CU6,FFC81C4F-0CB8-4972-A18D-4E4C62BFC19B,23,Peter Hedberg,0589561178823,S,Västernorrlands län,Nej,sakfrågan,348,man,1990,2023-04-19

In [7]:
votering_202223.columns = [
    'rm',
    'beteckning',
    'votering_id',
    'punkt',
    'namn',
    'intressent_id',
    'parti',
    'valkrets',
    'rost',
    'avser',
    'banknummer',
    'kön',
    'fodd',
    'system_datum'
]

votering_202223

,rm,beteckning,votering_id,punkt,namn,intressent_id,parti,valkrets,rost,avser,banknummer,kön,fodd,system_datum
0,2022/23,UU15,008484EA-7970-4559-BEA7-E2F6454E7571,5,Helena Bouveng,0729710260118,M,Jönköpings län,Ja,sakfrågan,10,kvinna,1962,2023-05-10
1,2022/23,UU15,008484EA-7970-4559-BEA7-E2F6454E7571,5,Mattias Jonsson,0499755198526,S,Göteborgs kommun,Ja,sakfrågan,18,man,1974,2023-05-10
2,2022/23,UU15,008484EA-7970-4559-BEA7-E2F6454E7571,5,Merit Frost Lindberg,0533104339313,M,Stockholms kommun,Ja,sakfrågan,26,kvinna,1973,2023-05-10
3,2022/23,UU15,008484EA-7970-4559-BEA7-E2F6454E7571,5,Jimmie Åkesson,051207517226,SD,Jönköpings län,Frånvarande,sakfrågan,34,man,1979,2023-05-10
4,2022/23,UU15,008484EA-7970-4559-BEA7-E2F6454E7571,5,Maj Karlsson,0198917587520,V,Göteborgs kommun,Frånvarande,sakfrågan,42,kvinna,1980,2023-05-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196830,2022/23,CU6,FFC81C4F-0CB8-4972-A18D-4E4C62BFC19B,23,Carl B Hamilton,0477013214601,L,Stockholms kommun,Frånvarande,sakfrågan,316,man,1946,2023-04-19
196831,2022/23,CU6,FFC81C4F-0CB8-4972-A18D-4E4C62BFC19B,23,Rebecka Le Moine,0546731406922,MP,Östergötlands län,Avstår,sakfrågan,324,kvinna,1990,2023-04-19
196832,2022/23,CU6,FFC81C4F-0CB8-4972-A18D-4E4C62BFC19B,23,Emma Ahlström Köster,0360160202728,M,Skåne läns södra,Ja,sakfrågan,332,kvinna,1987,2023-04-19
196833,2022/23,CU6,FFC81C4F-0CB8-4972-A18D-4E4C62BFC19B,23,Camilla Hansén,0692076685824,MP,Örebro län,Avstår,sakfrågan,340,kvinna,1976,2023-04-19
196834,2022/23,CU6,FFC81C4F-0CB8-4972-A18D-4E4C62BFC19B,23,Peter Hedberg,0589561178823,S,Västernorrlands län,Nej,sakfrågan,348,man,1990,2023-04-19

In [8]:
anforande_202223.loc[1]

dok_id                                  HA091
dok_rm                                2022/23
dok_nummer                                  1
dok_datum                 2022-09-26 00:00:00
avsnittsrubrik      Val av förste vice talman
kammaraktivitet                           NaN
anforande_nummer                           11
talare                         Annie Lööf (C)
parti                                       C
intressent_id                   0862868280923
rel_dok_id                                NaN
replik                                      N
Name: 1, dtype: object

In [11]:
print(len(anforande_202324[0]))

KeyError: 0

In [12]:
text = "HB09100	2023/24	100	2024-04-17 00:00:00	Förbättrade möjligheter att ändra kön	ärendedebatt	1	Yasmine Bladelius (S)	S	0996640018922	HB01SoU22	N"
print(len(text))

142

In [12]:
from api_caller import fetch_document_html
from langchain_community.document_transformers import BeautifulSoupTransformer
from langchain_core.documents import Document

def get_documents(dok_ids: list[str]) -> list[dict[str, str]]:
    """
    Fetches documents by their IDs and returns a list of dictionaries containing the document content.
    """
    documents = []
    bs_transformer = BeautifulSoupTransformer()
    
    try:
        if not isinstance(dok_ids, list):
            print("Invalid input: dok_ids must be a list.")
            raise TypeError("dok_ids must be a list.")
        if len(dok_ids) == 0:
            print("No document IDs provided.")
            raise ValueError("No document IDs provided.")
        else:        
            for dok_id in dok_ids:
                document = {}
                fetched_doc = fetch_document_html(dok_id)
                cleaned = bs_transformer.transform_documents([fetched_doc], tags_to_extract=["p", "h1", "h2", "h3", "li"])

                document["dok_id"] = dok_id
                document["innehåll"] = cleaned[0].page_content

                documents.append(document)

            return documents
    
    except Exception as e:
        print(f"Error fetching documents: {e}")

documents = get_documents("sgf")
print(documents)

Invalid input: dok_ids must be a list.
Error fetching documents: dok_ids must be a list.
None

In [3]:
personer = pd.read_csv("documents/personer/personer")

personer.columns

Index(['Förnamn', 'Efternamn', 'Iort', 'Parti', 'Id', 'Kön', 'Född',
       'Valkrets', 'Status', 'Webbadress', 'Epostadress', 'Telefonnummer',
       'Titel', 'Uppdragstyp', 'Uppdragsorgan', 'Uppdragsroll',
       'Uppdragsrollstatus', 'From', 'Tom'],
      dtype='object')

In [22]:
columns = {
    'Förnamn': 'förnamn',
    'Efternamn': 'efternamn',
    'Parti': 'parti',
    'Id': 'intressent_id',
    'Kön': 'kön',
    'Född': 'född',
    'Valkrets': 'valktrets',

}

cleaned = pd.read_csv("documents/personer/personer", header=0, usecols=columns)

cleaned_copy = cleaned.rename(columns=columns).drop_duplicates(subset=['intressent_id']).copy()

cleaned_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 349 entries, 0 to 8723
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   förnamn        349 non-null    object
 1   efternamn      349 non-null    object
 2   parti          349 non-null    object
 3   intressent_id  349 non-null    int64
 4   kön            349 non-null    object
 5   född           349 non-null    int64
 6   valktrets      349 non-null    object
dtypes: int64(2), object(5)
memory usage: 21.8+ KB

In [29]:
DATABASE_URL = "postgresql+psycopg2://gov_check_user:gov_check_pw@localhost:5432/gov_check_db"

from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

engine = create_engine(
    DATABASE_URL,
    pool_size=5,
    max_overflow=10,
    pool_pre_ping=True
)

SessionLocal = sessionmaker(
    autocommit=False,
    autoflush=False,
    bind=engine
)

# with SessionLocal() as session:
#     with session.begin():
#         session.execute(text("INSERT INTO votering (rm,beteckning,hangar_id,votering_id,punkt,namn,intressent_id,parti,valkrets,valkretsnummer,iort,rost,avser,votering,banknummer,fornamn,efternamn,kon,fodd,datum) VALUES ('2022/23','UU15',5167346,'008484EA-7970-4559-BEA7-E2F6454E7571',5,'Merit Frost Lindberg','0533104339313','M','Stockholms kommun',1,'','Ja','sakfrågan','huvud',26,'Merit','Frost Lindberg','kvinna',1973,'2023-05-10');"))


# Instantiate a session, then call .begin() on it
with SessionLocal() as sess:
    with sess.begin():
        result = sess.scalars(text("SELECT id FROM votering WHERE intressent_id = '083953568015'"))
        print(result.all())

[150, 538, 742, 1183, 1409, 1788, 2370, 2542, 2805, 3277, 3533, 3883, 4355, 4856, 5205, 5432, 5720, 6209, 6601, 6737, 7116, 7576, 7753, 8236, 8389, 8830, 9118, 9497, 9909, 10227, 10682, 11008, 11212, 11530, 12014, 12349, 12883, 13112, 13368, 13685, 14066, 14520, 14732, 15081, 15462, 16011, 16279, 16509, 16796, 17145, 17613, 17874, 18254, 18632, 19165, 19362, 19649, 19967, 20409, 20635, 20984, 21364, 21775, 22031, 22380, 22822, 23109, 23702, 23869, 24249, 24535, 24792, 25141, 25581, 25975, 26188, 26537, 27192, 27235, 27736, 27964, 28344, 28661, 29011, 29329, 29678, 30319, 30376, 30756, 31289, 31621, 31772, 32532, 33125, 33168, 33736, 34521, 34870, 35037, 36083, 37736, 39661, 39985, 40908, 41195, 44078, 44367, 44808, 47888, 48341, 50042, 50269, 51788, 52045, 53565, 53820, 55448, 55810, 55853, 57729, 57978, 58951, 59054, 61045, 61088, 62577, 63016, 64733, 66537, 66765, 68417, 69625, 69844, 72347, 73365, 73775, 76401, 77785, 78102, 78343, 79193, 79267, 80632, 82377, 82757, 84183, 84595, 86173, 86216, 87961, 88341, 90055, 91800, 92211, 93726, 93954, 95670, 96224, 97887, 98113, 99539, 99982, 101616, 103317, 103849, 105804, 106260, 107218, 109861, 110112, 111755, 112042, 114136, 114515, 116036, 116261, 118807, 120541, 120921, 122635, 123865, 124001, 125653, 126002, 127522, 127778, 129410, 129508, 129903, 131268, 131740, 133485, 133680, 135106, 135425, 137476, 138915, 139444, 140846, 141102, 141402, 142798, 143209, 145259, 145607, 147248, 147471, 147733, 149599, 151031, 151222, 151509, 153255, 155090, 155349, 157007, 158899, 160794, 161024, 162832, 162996, 164423, 164741, 166547, 166835, 168384, 168642, 170356, 170705, 172101, 172481, 174269, 176002, 176363, 178108, 179810, 180235, 181799, 181964, 183717, 185899, 187426, 189202, 189711, 191295, 191676, 193451, 195166, 195484, 196985, 197351, 198366, 200052, 200492, 202308, 202523, 203890, 204209, 206229, 206272, 207792, 208235, 209793, 210142, 211687, 211917, 213694, 215652, 217298, 217590, 217789, 219390, 219757, 221310, 223267, 223538, 224906, 225424, 226967, 227397, 228730, 229263, 230952, 231113, 232959, 234541, 234890, 236407, 236819, 238471, 238760, 240187, 240709, 242281, 244056, 244343, 246351, 247896, 248196, 249384, 251066, 251474, 253161, 254935, 255224, 256834, 257058, 257287, 257986, 258347, 260280, 260459, 261189, 261707, 261763, 263159, 265471, 267304, 267439, 270170, 270519, 272059, 272428, 274541, 274823, 276727, 276861, 277119, 277654, 279017, 279274, 279562, 281112, 281307, 283083, 284828, 285269, 286665, 287027, 289539, 291734, 291870, 292218, 293933, 295099, 295267, 297012, 297361, 299019, 299137, 300764, 300851, 301200, 303386, 303767, 305914, 306148, 307163, 307482, 308602, 310493, 310915, 310972, 311396, 312836, 313372, 314711, 314811, 315160, 316164, 316382, 319759, 320076, 320395, 320775, 322055, 325692, 326232, 326358, 326677, 327057, 327375, 329330, 329605, 329818, 331244, 331625, 332513, 332732, 334573, 335929, 336160, 337620, 338110, 339621, 340045, 340424, 340667, 342033, 342382, 343590, 344599, 344999, 345829, 345903, 346252, 347225, 347330, 349711, 350164, 350952, 351169, 353158, 353231, 354278, 354597, 356215, 356342, 357451, 357769, 358559, 358859, 359165, 360474, 360792, 360910, 362581, 362654, 363826, 364235, 365722, 366071, 366114, 367633, 367920, 370713, 371031, 372702, 373051, 373187, 375979, 376266, 378203, 379682, 379968, 380074, 381544, 381950, 383413, 383665, 383943, 385401, 385876, 387360, 387433, 387752, 389326, 389672, 391242, 391591, 393080, 394414, 394824, 395692, 396017, 397076, 397175, 398747, 398950, 399462, 399724, 401631, 402759, 404504, 404853, 406660, 408465, 410210, 410499, 413352, 413640, 416052, 416370, 418557, 418888, 420333, 420558, 422260, 422539, 422727, 424298, 424427, 426204, 428042, 428357, 429184, 429405, 431334, 431573, 432584, 432865, 434960, 435216, 438737, 439248, 440800, 442576, 442924, 444792, 446415, 446925, 448031, 448160, 449176, 450376, 450695, 452410, 453364, 453713, 455264, 455720, 456627, 457045, 458435, 458861, 458948, 460435, 460693, 461654, 462046, 462120, 463660, 464973, 466748, 467006, 468083, 468371, 470366, 470465, 471381, 471574, 473375, 474365, 474684, 476704, 477611, 477961, 478871, 479337, 480800, 480966, 482012, 482554, 483951, 484268, 485417, 485656, 487087, 487523, 488613, 490450, 491904, 493707, 493909, 494769, 495062, 496597, 496867, 497020, 497863, 498362, 498416, 499781, 500161, 501906, 503713, 503999, 505745, 507674, 507974, 509510, 509677, 511452, 513516, 515335, 515640, 516975, 517323, 519282, 520983, 521101, 523121, 523238, 524652, 525202, 526567, 526873, 527034, 528705, 528929, 530646, 530873, 532531, 532742, 534376, 536077, 536457, 537504, 539395, 539627, 541269, 541575, 543351, 543668, 544981, 545273, 545531, 547115, 547245, 549021, 549401, 550692, 550828, 551239, 552921, 553209, 553967, 554435, 555578, 555774, 557107, 557502, 559809, 560158, 561847, 564164, 564408, 566122, 566440, 567898, 568491, 33998, 37116, 37417, 38360, 38494, 40272, 40650, 42242, 42621, 43700, 45995, 46335, 47688, 49484, 49694, 51060, 51316, 52908, 53184, 54262, 54763, 56233, 56551, 58296, 59998, 60041, 60512, 61940, 62397, 64066, 64320, 65687, 66160, 67825, 68130, 70329, 70604, 71663, 71938, 74093, 74412, 75428, 75837, 77307, 79800, 80027, 80283, 81043, 81422, 83106, 84926, 87467, 87735, 88844, 89101, 91513, 93227, 95381, 97066, 97507, 98961, 99160, 100904, 101284, 102829, 103173, 105566, 107767, 108103, 108296, 110516, 110707, 112639, 114865, 115245, 116885, 116959, 118281, 118355, 120026, 120160, 121844, 122163, 124455, 124788, 126501, 128182, 128465, 130282, 131966, 132375, 134226, 135834, 137730, 137958, 139613, 139993, 141707, 143545, 143891, 145043, 146748, 148473, 148811, 149036, 150462, 152526, 152875, 154302, 154788, 156168, 156488, 158416, 158489, 160234, 162036, 162329, 163799, 164131, 165788, 166255, 167882, 169584, 169933, 170006, 171403, 171721, 173497, 173877, 175361, 175774, 177502, 177685, 179215, 179552, 180917, 181319, 183054, 183424, 184756, 185137, 185332, 186925, 187252, 189041, 190037, 190342, 192269, 194406, 194786, 196562, 198888, 198943, 200994, 201299, 202886, 203174, 204557, 205010, 206744, 208490, 208715, 210766, 210809, 213039, 213283, 214764, 215245, 216894, 218793, 219021, 220538, 220581, 221023, 222462, 222737, 224630, 226196, 226545, 228060, 228413, 230066, 230538, 231883, 232360, 232447, 233800, 233993, 234283, 235850, 236243, 237595, 237800, 238124, 239140, 239458, 240823, 241265, 242830, 243051, 245453, 245771, 246531, 246830, 247136, 248576, 248912, 250750, 251673, 251991, 253552, 253921, 256136, 256485, 258653, 259002, 260777, 262492, 262884, 264555, 264904, 266606, 266680, 268394, 269441, 269865, 271404, 271743, 274070, 275904, 276103, 278459, 278778, 280322, 280669, 282255, 282660, 282734, 283549, 283843, 285557, 287364, 287836, 288742, 289047, 290547, 290823, 292690, 294396, 294662, 296418, 296755, 298121, 298544, 300066, 300319, 301580, 301898, 303992, 304403, 305668, 306466, 306815, 309002, 309418, 312256, 312399, 313536, 313764, 315627, 317517, 317603, 318754, 319305, 319611, 322446, 322489, 322898, 323597, 324008, 325238, 325281, 327754, 330198, 332123, 333963, 334204, 335010, 335053, 335599, 337209, 338299, 338635, 340986, 342761, 343111, 345480, 347740, 348116, 349074, 349537, 350715, 352534, 355124, 355295, 355718, 358239, 359832, 361395, 363184, 363415, 365067, 366997, 367161, 368820, 369168, 370550, 372108, 373853, 374404, 374490, 374974, 376846, 378448, 380729, 380772, 382168, 384355, 386069, 388224, 390001, 390195, 392246, 393598, 393822, 394034, 396189, 396667, 398375, 400789, 401168, 403199, 403691, 405202, 407039, 407531, 408998, 409072, 410786, 413086, 414656, 414974, 416750, 418028, 418208, 419817, 420037, 421911, 423264, 423381, 425052, 425246, 425444, 425824, 427631, 428677, 430941, 431881, 432105, 433626, 433968, 434200, 434780, 436424, 436642, 437965, 438187, 438554, 440015, 440352, 440543, 442153, 442315, 443491, 443696, 445202, 445643, 447082, 447462, 449787, 449996, 451045, 451394, 452756, 453106, 454593, 455066, 455982, 456156, 457858, 458006, 459358, 461042, 462500, 464140, 464183, 464693, 465405, 465701, 465958, 467536, 467735, 469250, 469580, 469798, 471076, 472422, 472865, 473000, 473912, 473986, 475793, 476049, 476901, 477186, 478266, 478584, 480124, 480420, 481565, 481939, 483684, 484560, 485043, 486781, 487751, 488006, 488264, 489966, 490171, 492339, 492544, 492861, 493305, 495499, 495899, 496004, 498796, 500479, 500950, 502403, 502603, 504504, 506247, 506718, 508409, 508630, 510076, 510313, 511909, 512258, 512376, 513864, 514121, 516015, 516184, 517874, 518083, 519588, 519674, 520054, 521511, 521921, 523775, 525332, 527483, 529247, 529613, 531352, 532936, 533346, 535503, 535845, 538128, 538433, 540039, 540340, 542665, 542829, 544632, 546347, 546766, 547654, 547943, 550299, 552049, 552350, 552480, 554667, 555047, 556119, 556422, 557806, 558108, 559293, 559551, 560960, 561467, 563074, 564931, 565313, 567259, 568840, 568913, 571101, 571493, 571675, 574075, 575196, 577216, 577290, 578848, 579127, 583760, 584196, 585785, 586076, 587759, 588109, 589505, 589823, 591418, 591778, 593344, 593767, 595713, 597414, 599246, 601052, 601371, 602955, 603221, 603434, 605098, 605313, 606754, 606986, 607273, 608601, 608669, 610358, 32183, 35490, 35673, 36408, 36812, 38907, 39225, 41719, 41924, 43095, 43320, 45340, 45689, 46623, 46841, 47159, 48524, 48904, 50742, 52456, 54974, 57206, 57249, 59436, 61468, 63444, 63531, 65051, 65429, 67144, 67491, 68982, 69177, 71166, 71333, 72696, 73047, 74792, 75109, 76706, 76978, 78538, 81884, 82194, 83599, 84022, 85475, 85642, 86702, 87067, 89571, 89860, 90525, 90889, 91133, 92498, 92940, 94473, 94592, 94941, 96399, 96777, 98431, 100176, 100616, 102087, 102424, 104146, 104364, 105019, 105123, 106520, 106983, 108613, 108901, 109368, 111087, 111344, 112956, 113181, 113744, 113787, 115532, 117308, 117657, 119328, 119507, 121422, 121619, 123123, 123331, 125061, 125304, 126832, 127049, 128838, 130600, 131194, 132726, 132982, 134627, 134990, 136385, 136503, 136882, 138308, 138653, 140372, 142349, 142557, 144212, 144529, 145895, 146349, 148064, 149886, 150269, 151952, 152208, 153635, 154107, 155853, 157369, 157442, 157945, 159463, 159642, 159886, 161474, 161631, 163345, 165090, 165591, 167319, 167533, 169052, 171220, 172921, 173210, 174775, 175073, 176651, 177047, 178535, 178762, 180739, 182221, 182802, 184117, 184316, 186092, 186379, 188037, 188186, 188534, 190689, 191009, 192405, 192822, 193010, 193769, 194057, 195833, 196151, 197547, 198062, 199398, 199641, 201416, 201865, 203717, 205225, 205604, 207151, 207480, 209183, 209444, 211251, 212311, 212772, 214212, 214299, 215957, 216075, 216548, 218362, 220075, 221934, 222283, 223984, 224102, 225729, 225938, 227561, 229368, 229716, 231431, 233451, 235331, 237150, 239776, 241815, 241932, 243515, 243783, 244662, 245011, 247516, 249701, 250159, 250307, 252564, 252820, 254304, 254619, 255481, 257575, 259382, 259731, 262317, 263756, 264163, 264298, 265783, 266039, 267770, 268106, 268923, 269154, 270961, 272613, 273116, 273311, 273866, 275287, 275405, 277847, 280032, 281919, 284273, 284508, 286093, 286360, 287999, 288468, 289819, 290257, 291182, 293130, 293204, 293522, 295865, 296170, 297741, 299653, 302429, 302658, 302945, 304720, 305070, 307861, 308180, 309824, 310187, 311774, 314375, 316819, 316998, 318100, 318392, 321124, 321535, 323187, 324358, 324706, 328103, 328559, 329033, 330607, 330865, 333222, 333571, 336581, 336891, 339129, 339346, 341598, 341990, 343970, 344188, 346631, 348507, 348927, 351762, 351805, 352154, 353774, 353899, 356691, 357101, 359789, 361839, 362111, 364492, 364811, 366600, 368208, 369418, 369666, 369953, 371410, 371917, 373534, 375218, 375537, 377101, 377588, 377662, 378940, 379333, 381182, 382823, 383084, 384905, 385266, 386618, 386705, 388712, 388799, 390850, 391017, 392320, 392699, 395142, 397628, 397934, 400089, 400316, 401974, 402061, 402410, 403868, 404278, 405735, 405931, 406250, 407823, 408025, 409696, 409739, 411353, 411747, 412113, 412488, 412591, 414151, 414400, 415503, 415777, 417068, 417571, 419381, 421213, 421286, 423699, 426783, 427106, 427189, 429938, 430012, 430361, 433122, 435720, 436068, 437159, 437340, 439698, 441372, 441590, 444072, 444290, 445748, 446066, 448509, 448827, 451650, 452055, 454185, 457339, 459707, 460162, 462942, 463398, 466338, 468826, 472167, 475126, 475474, 479663, 482741, 483120, 486127, 486167, 489022, 489372, 490903, 491298, 491436, 494350, 497429, 499144, 499432, 501440, 501556, 502983, 503485, 504850, 505109, 505439, 506896, 507326, 509147, 510692, 511102, 512694, 513074, 514543, 515004, 516533, 518340, 518793, 520403, 522294, 522647, 523999, 524517, 525913, 525956, 527832, 528081, 529899, 530249, 531705, 531920, 533696, 533983, 534813, 535336, 537081, 537155, 538826, 538930, 540614, 541840, 542101, 543991, 544104, 545880, 548385, 548641, 549719, 551495, 553620, 556818, 558413, 558915, 560507, 562209, 562558, 562725, 563419, 563854, 565499, 565917, 567026, 570149, 570279, 572055, 572416, 572784, 575667, 575955, 577914, 579353, 579763, 580780, 581889, 582308, 582678, 583034, 584545, 584850, 584937, 587137, 587499, 588580, 590264, 590614, 592223, 592572, 594178, 596603, 597014, 597807, 597986, 599731, 600006, 601855, 604132, 604730, 606226, 607885, 611841, 612286, 614438, 614633, 614981, 615424, 617743, 621146, 622720, 625321, 625544, 626425, 626774, 626910, 628274, 628562, 630526, 632114, 632401, 634325, 634526, 636192, 636240, 638073, 639788, 640141, 641652, 641824, 642173, 643722, 643976, 644904, 645146, 645374, 646785, 647059, 648102, 648482, 650679, 651044, 652131, 653841, 654256, 655916, 656195, 657745, 657970, 659483, 659623, 661489, 661958, 663340, 663539, 665203, 665647, 667166, 667623, 669170, 669575, 670973, 671285, 672943, 673295, 674765, 675006, 676777, 677073, 678593, 678879, 680850, 681095, 683062, 683385, 685336, 685510, 686906, 687285, 689729, 691659, 693408, 693600, 695221, 697439, 699122, 700867, 701303, 702757, 703080, 703262, 705085, 707000, 707109, 708483, 708863, 710394, 710639, 712415, 712731, 714248, 714722, 716419, 716696, 718556, 720167, 720534, 722005, 722155, 724073, 724219, 725798, 726118, 727840, 729544, 729990, 731548, 731896, 733446, 733642, 735449, 735793, 737277, 737543, 739096, 739195, 739637, 741285, 743188, 745332, 746792, 747058, 748834, 749184, 750816, 752580, 752929, 754356, 754843, 756388, 758639, 760352, 760576, 762258, 763974, 764509, 766479, 766766, 768678, 770471, 770698, 772195, 772474, 774095, 774640, 775687, 775932, 777329, 777647, 778754, 780589, 780933, 782428, 782471, 782851, 784658, 786875, 787267, 787357, 788960, 789133, 791029, 792742, 792941, 794717, 796431, 796935, 798334, 798691, 800331, 800619, 802321, 802364, 803368, 803442, 803791, 805628, 807365, 807630, 809220, 809552, 811306, 812964, 813245, 815656, 818190, 819291, 819580, 819814, 821364, 821776, 822441, 822761, 824623, 824854, 826313, 826630, 828496, 828691, 830345, 830695, 832060, 832408, 833898, 834163, 835083, 836217, 837818, 838821, 839765, 840622, 841598, 842690, 843732, 844469, 845477, 846521, 847385, 848525, 849192, 850208, 851311, 854200, 855567, 856110, 859088, 860057, 860623, 861862, 863485, 865742, 865913, 866417, 868189, 871908, 609280, 609460, 609716, 611205, 611584, 613360, 613555, 614027, 615955, 616029, 618197, 618565, 619401, 619581, 621356, 621644, 623284, 623446, 623838, 624149, 624405, 625931, 627957, 629776, 630020, 631509, 631733, 633513, 633925, 635324, 635850, 637407, 637665, 639136, 639524, 641153, 643126, 643313, 645786, 646134, 646361, 648804, 649181, 649974, 650344, 652488, 652893, 652992, 654461, 654923, 656482, 658288, 658759, 660214, 660363, 662220, 662506, 663962, 664466, 666060, 667773, 668238, 669773, 670093, 671550, 671900, 673593, 673928, 675611, 675905, 677716, 677802, 679353, 679516, 681323, 682936, 684402, 684843, 686329, 686650, 688122, 688479, 688621, 690015, 690366, 691962, 692142, 692460, 693825, 694386, 695733, 696012, 696268, 697875, 698075, 699715, 699941, 701716, 702006, 703752, 705342, 705689, 707634, 707816, 709377, 709561, 711203, 711339, 713018, 713460, 714948, 715214, 717045, 718696, 719059, 720823, 722505, 723004, 724754, 724979, 726492, 726693, 728244, 728497, 730414, 730501, 732457, 732657, 734048, 734340, 736111, 736463, 737952, 738178, 740017, 741662, 742014, 743658, 743887, 745599, 745980, 747437, 747785, 747943, 749622, 749876, 751247, 751441, 753155, 753548, 755085, 755411, 756951, 757024, 757466, 758904, 759119, 760987, 762858, 763181, 764764, 765841, 766161, 767905, 768193, 769864, 770090, 771713, 773930, 777011, 779287, 779361, 779710, 781987, 784034, 784216, 785798, 786085, 787768, 789668, 789791, 791252, 791575, 793426, 795220, 795570, 797315, 798936, 799376, 800968, 801408, 803019, 804643, 805022, 805247, 806547, 806932, 808863, 810453, 810771, 812285, 812547, 814376, 814732, 816155, 816413, 817371, 817943, 820380, 822001, 823715, 824095, 825613, 825933, 827647, 827945, 829737, 829965, 831486, 831710, 833456, 835546, 836566, 837591, 838477, 839451, 841317, 842415, 843414, 844103, 845154, 845984, 847160, 848083, 849002, 849895, 851061, 851796, 852013, 852985, 853482, 854547, 856900, 857353, 859463, 859691, 860771, 861120, 862074, 863097, 863899, 864560, 865021, 865392, 866732, 867084, 867834, 868512, 868888, 869237, 869721, 870220, 871489, 872225, 872575, 567736, 569293, 569581, 570752, 573071, 573558, 574283, 574467, 574816, 576336, 576591, 578081, 578399, 580226, 580430, 581252, 581662, 583192, 585379, 586333, 586744, 588928, 589309, 590991, 592790, 593056, 594666, 594958, 595155, 595849, 596312, 598505, 598578, 598957, 600333, 600673, 602209, 602650, 603783, 605790, 605877, 608002, 610506, 610794, 612508, 612948, 616347, 616758, 617351, 617425, 618852, 620020, 620186, 620535, 621962, 622311, 624854, 627384, 627545, 629217, 629438, 630868, 631311, 632811, 633161, 635052, 636585, 636969, 638488, 638869, 640612, 640769, 642594, 644484, 647622, 647973, 649700, 651309, 651652, 653479, 655086, 655633, 657135, 657427, 659111, 660988, 661243, 662888, 664694, 664995, 666487, 666787, 668463, 668821, 670628, 672404, 672819, 674335, 676212, 676521, 678332, 680187, 680336, 681763, 682137, 682339, 683921, 684270, 685922, 687747, 689081, 689315, 690775, 691095, 692870, 694647, 694965, 696725, 696977, 698598, 698862, 700287, 700737, 702324, 704202, 704488, 704644, 706195, 706479, 708271, 710065, 711841, 712207, 713839, 715494, 716079, 717474, 717738, 717969, 719329, 719798, 721232, 721613, 723171, 723644, 725468, 727069, 727339, 728994, 729289, 731066, 731259, 732974, 734658, 735007, 736967, 738683, 740483, 740653, 740970, 742367, 742742, 744353, 744615, 744809, 746175, 748265, 750045, 750363, 752024, 752358, 754159, 755691, 755978, 757998, 758067, 759437, 759816, 761350, 761782, 761880, 763461, 763811, 765233, 765611, 767421, 767464, 769014, 769270, 771122, 771408, 773005, 773048, 773397, 774947, 775142, 776216, 776569, 777934, 778482, 780028, 781075, 781636, 783261, 783548, 784914, 785418, 786372, 788205, 788526, 790180, 790498, 791955, 792304, 793919, 794203, 794428, 795856, 796187, 797663, 797917, 799696, 799983, 801759, 804347, 805976, 806203, 808205, 808359, 809848, 810253, 811722, 811849, 813687, 814005, 815197, 815399, 816797, 817101, 818724, 818852, 820698, 821096, 823074, 823601, 825266, 826887, 827297, 828946, 829390, 831199, 832727, 833072, 834503, 835386, 836119, 837070, 838081, 839222, 840101, 840976, 842016, 842848, 844790, 845732, 846903, 847857, 849650, 850762, 852474, 852654, 853852, 854710, 855063, 855792, 856614, 857567, 858074, 858472, 858769, 861466, 862423, 862986, 864256, 867275, 869527, 870419, 870892, 871147]

In [13]:
from pathlib import Path

DOCUMENTS_PATH = Path('documents')

def utc_now():
    return datetime.now(timezone.utc)

def load_sql_paths(directory: str) -> list[Path]:
    documents_path = Path(DOCUMENTS_PATH) / directory
    return list(documents_path.glob("*.sql"))

print(load_sql_paths("anforanden"))

[PosixPath('documents/anforanden/anforande-202223.sql'), PosixPath('documents/anforanden/anforande-202324.sql'), PosixPath('documents/anforanden/anforande-202425.sql'), PosixPath('documents/anforanden/anforande-202526.sql')]

In [ ]:
import re

sql_path = Path("documents/anforanden/anforande-202223.sql")
with sess.begin():
            for path in load_sql_paths(sql_path):
                print(f"Processing: {path.name}")
                raw_sql = path.read_text(encoding="utf-8")
                inserts = re.findall(r'INSERT INTO .+?;', raw_sql, re.DOTALL)

                for insert in inserts:
                    sess.execute(text(insert))

In [18]:
sql_path = Path("documents/anforanden/anforande-202223.sql")

raw_sql = sql_path.read_text(encoding="utf-8")
inserts = re.findall(r'INSERT INTO .+?;', raw_sql, re.DOTALL)

print(inserts[2])

INSERT INTO anforande (dok_hangar_id,dok_id,dok_titel,dok_rm,dok_nummer,dok_datum,avsnittsrubrik,underrubrik,kammaraktivitet,anforande_id,anforande_nummer,talare,parti,anforandetext,intressent_id,rel_dok_id,replik,systemdatum)
    VALUES (5147373,'HA091','Protokoll 2022/23:1 Måndagen den 26 september','2022/23',1,'2022-09-26 00:00:00','Val av förste vice talman','','','f0d46b26-e94e-ed11-9177-901b0eac4c70',11,'Annie Lööf (C)','C','<p>Fru ålderspresident och ärade ledamöter av Sveriges riksdag! Centerpartiet har stort förtroende för Kenneth G Forslund som riksdagens förste vice talman, och vi står bakom förslaget. Vi tycker att det är rimligt att riksdagens största parti innehar vice talmansposten och kommer därför att aktivt rösta ja till Kenneth G Forslund som förste vice talman. Vi hoppas på ett lika brett stöd här i kammaren som vid valet av talman - det vore för Sveriges bästa.</p><p>Överläggningen var härmed avslutad.</p><p>Kammaren valde med acklamation <em>Kenneth G Forslund</em><em> </em>(S) till förste vice talman.</p><p>(Applåder)</p>','0862868280923','','N','2022-10-18 15:31:55');